# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Jiwon Seon's Portfolio
  params:
    description: This is Jiwon Seon's Portfolio.
  weight: 2
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko-kr
  contentDir: content/ko
  title: μ„ μ§€μ› ν¬νΈν΄λ¦¬μ¤
  weight: 1
  params:
    description: μ „λ¶λ€ μ„ μ§€μ› ν¬νΈν΄λ¦¬μ¤ νμ΄μ§€μ…λ‹λ‹¤.
  menu:
    main:
      - name: π 
        url: "/"
        weight: 1
